name: cs_monero_flutter_libs_ios
description: Ios implementation of cs_monero_flutter_libs
version: 1.0.0-pre.0
repository: https://github.com/cypherstack/cs_monero
homepage: https://github.com/cypherstack/cs_monero
issue_tracker: https://github.com/cypherstack/cs_monero/issues

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cs_monero_flutter_libs_platform_interface: 1.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: CsMoneroFlutterLibsIosPlugin
        dartPluginClass: CsMoneroFlutterLibsIos
